patterns = [
    (r'hi|hello|hey|greetings', ['Hello! How can I assist you today?']),
    (r'howdy|what\'s up', ['Howdy! What can I do for you today?']),
    (r'what is your name?', ['I am a chatbot created to assist you.']),
    (r'how are you\??', ['I am just a program, but I am functioning as expected!']),
    (r'(.*) your name\??', ['I am a chatbot, and I don’t have a name.']),
    (r'how old are you\??', ['I don’t have an age like humans do. I exist in the digital realm!']),
    (r'what can you do\??', ['I can assist you with various questions and provide information. Just ask!']),
    (r'what is your purpose\??', ['My purpose is to assist and provide information to the best of my ability.']),
    (r'can you help me with (.*)\??', ['I can try to help with that. What do you need assistance with?']),
    (r'how was your day\??', ['I don’t experience days, but I’m here to help you!']),
    (r'what do you like to do\??', ['I don’t have personal likes or dislikes. My only job is to assist you.']),
    (r'tell me something interesting', ['Did you know honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.']),
    (r'tell me a joke', ['Why don’t scientists trust atoms? Because they make up everything!']),
    (r'do you know any jokes\??', ['Here’s a classic: Why did the scarecrow win an award? Because he was outstanding in his field!']),
    (r'what is your favorite color\??', ['I don’t have preferences, but I can tell you that blue is often associated with calmness.']),
    (r'(.*) my favorite color\??', ['I don’t know your favorite color, but I’d love to hear it if you’d like to share!']),
    (r'what is the weather like\??', ['I am not able to check the weather right now. You might want to use a weather app or website.']),
    (r'will it rain today\??', ['I don’t have weather capabilities, but a weather app or website should have the information you need.']),
    (r'bye|goodbye|see you|later', ['Goodbye! Have a great day!']),
    (r'talk to you later', ['Sure, talk to you later!']),
    (r'help|assistance', ['I’m here to help! What do you need assistance with?']),
    (r'where are you from\??', ['I exist in the digital realm and don’t have a physical location.']),
    (r'who created you\??', ['I was created by developers to assist and provide information.']),
    (r'(.*)', ['Sorry, I do not understand that. Can you please rephrase?'])
]
